name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v4.0.3
        with:
          major_pattern: 'major:'
          minor_pattern: 'feat:'
          patch_pattern: 'fix:'
          format: '${{version}}-prerelease${{increment}}'
        id: version

      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          echo "Version: ${{ steps.version.outputs.version }}"

      - name: Build Docker Image
        run: |
          echo "Building Docker image with version: ${{ steps.version.outputs.version }}"
          docker build -t mariogonzcardona/docker_graphql:${{ steps.version.outputs.version }} .
          docker build -t mariogonzcardona/docker_graphql:latest .

      - name: Push Docker Image
        run: |
          echo "Pushing Docker image with version: ${{ steps.version.outputs.version }}"
          docker push mariogonzcardona/docker_graphql:${{ steps.version.outputs.version }}
          docker push mariogonzcardona/docker_graphql:latest
