name: Docker Image CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "Proceso de Login en Docker Hub"
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          echo "Login exitoso"
      
      - name: Build Docker Image
        run: |
          echo "Construyendo la imagen de Docker"
          docker build -t mariogonzcardona/docker_graphql:1.0.0 .
          echo "Imagen construida"
      
      - name: Push Docker Image
        run: |
          echo "Subiendo la imagen de Docker"
          docker push mariogonzcardona/docker_graphql:1.0.0
          echo "Imagen subida"
