name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      NEW_VERSION: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v4.0.3
        with:
          major_pattern: 'major:'
          minor_pattern: 'feat:'
          format: '${{major}}.${{minor}}.${{patch}}-prerelease${{increment}}'
        id: version

      - name: Set version environment variable
        run: |
          echo "NEW_VERSION=${{ steps.version.outputs.version }}" >> $GITHUB_ENV

      - name: Docker Login
        run: |
          echo "Inicio del Login"
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          echo "Versión: $NEW_VERSION"

      - name: Build Docker Image
        run: |
          echo "Building Docker image with version: $NEW_VERSION"
          docker build -t mariogonzcardona/docker_graphql:$NEW_VERSION .
          docker build -t mariogonzcardona/docker_graphql:latest .

      - name: Push Docker Image
        run: |
          echo "Pushing Docker image with version: $NEW_VERSION"
          docker push mariogonzcardona/docker_graphql:$NEW_VERSION
          docker push mariogonzcardona/docker_graphql:latest
