name: Docker Image CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v5.4.0
        with: 
          major_pattern: "major:"
          minor_pattern: "feat:"
          patch_pattern: "fix:"
          version_format: "${major}.${minor}.${patch}-${increment}"
        id: version
            
      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          NEW_VERSION: ${{ steps.version.outputs.version }}
        run: |
          echo "Proceso de Login en Docker Hub"
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          echo "Login exitoso"
          echo " Prueba de la nueva versión"
          echo "Nueva versión: $NEW_VERSION"

      # - name: Build Docker Image
      #   run: |
      #     echo "Construyendo la imagen de Docker"
      #     docker build -t mariogonzcardona/docker_graphql:1.0.0 .
      #     docker build -t mariogonzcardona/docker_graphql:latest .
      #     echo "Imagen construida"
      
      # - name: Push Docker Image
      #   run: |
      #     echo "Subiendo la imagen de Docker"
      #     docker push mariogonzcardona/docker_graphql:1.0.0
      #     docker push mariogonzcardona/docker_graphql:latest
      #     echo "Imagen subida"
